name: release

on:
  push:
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          key: v1-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            target
            ~/.cargo
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-linux-musl

      - name: Build the app
        run:
          cargo build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/toggl-cli-rs toggl-cli-rs-${{ github.event.release.tag_name }}-x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: toggl-cli-rs-${{ github.event.release.tag_name }}-x86_64-unknown-linux-musl
